<?xml version="1.0"?> 
<!DOCTYPE bookstore [ 
<!ELEMENT bookstore (book)> 
<!ELEMENT book (bookname,bookprice,bookauthor,booknumber,pages)> 
<!ELEMENT bookname (#PCDATA)> 
<!ELEMENT bookprice (#PCDATA)> 
<!ELEMENT bookauthor (#PCDATA)> 
<!ELEMENT booknumber (#PCDATA)> 
 
<!ELEMENT pages (#PCDATA)> 

]> 


<bookstore>
<book>
<bookname>War and Peace</bookname>
<bookauthor>leo tolstoy</bookauthor>
<bookprice>$2500</bookprice>
<ISBN>106543</ISBN>
<pages>400</pages>
</book>
<book>
<bookname>To Kill a Mockingbird</bookname>
<bookauthor>Harper Lee</bookauthor>
<bookprice>$500</bookprice>
<ISBN>109876</ISBN>
<pages>200</pages>
</book>
<book>
<bookname>The Great Gatsby</bookname>
<bookauthor>F. Scott Fitzgerald</bookauthor>
<bookprice>$1000</bookprice>
<ISBN>108754</ISBN>
<pages>270</pages>
</book>
<book>
<bookname>Things Fall Apart</bookname>
<bookauthor>Chinua Achebe</bookauthor>
<bookprice>$700</bookprice>
<ISBN>107654</ISBN>
<pages>150</pages>
</book>
<book>
<bookname>A Passage To India</bookname>
<bookauthor>E.M.Forster</bookauthor>
<bookprice>$400</bookprice>
<ISBN>105432</ISBN>
<pages>300</pages>
</book>
</bookstore>
